name: Build and Publish DevContainer

on:
  push:
    branches: [ main ]
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/build-devcontainer.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: shuttle-hq/shuttle-shellcon-devcontainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .devcontainer
        file: .devcontainer/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Make package public
      run: |
        # Wait a bit for the package to be available
        sleep 10
        
        # Make the shuttle-shellcon-devcontainer package public
        gh api --method PATCH /orgs/shuttle-hq/packages/container/shuttle-shellcon-devcontainer \
          --field visibility=public || echo "Failed to make package public, may already be public"
        
        # Also try making specific versions public
        PACKAGE_VERSIONS=$(gh api /orgs/shuttle-hq/packages/container/shuttle-shellcon-devcontainer/versions --jq '.[].id' 2>/dev/null || echo "")
        for version_id in $PACKAGE_VERSIONS; do
          gh api --method PATCH /orgs/shuttle-hq/packages/container/shuttle-shellcon-devcontainer/versions/$version_id \
            --field visibility=public || echo "Failed to make version $version_id public"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}