name: Update DevContainer Image

on:
  push:
    branches: [ main ]
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/update-devcontainer.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/update-devcontainer.yml'
  schedule:
    # Run weekly on Sundays at 2 AM UTC to update dependencies
    - cron: '0 2 * * 0'
  workflow_dispatch:
    # Allow manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: shuttle-hq/shuttle-shellcon-devcontainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=schedule,pattern={{date 'YYYYMMDD'}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .devcontainer
        file: .devcontainer/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update DevContainer to use new image
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      run: |
        # Update devcontainer.json with timestamp to force rebuild
        DATE=$(date +%Y%m%d)
        sed -i "s/\"name\": \"ShellCon Development Environment\"/\"name\": \"ShellCon Development Environment ($DATE)\"/" .devcontainer/devcontainer.json
        
        # Commit and push if there are changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add .devcontainer/devcontainer.json
          git commit -m "chore: update DevContainer dependencies ($DATE)

          🤖 Automated dependency update
          
          - Updated base image with latest dependencies
          - Refreshed Shuttle CLI to latest version
          - Updated Node.js and npm packages"
          git push
        fi